# Generated by Django 4.2.5 on 2023-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(default='', upload_to='user_imgs'),
        ),
    ]
