# Generated by Django 4.2.5 on 2023-10-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0002_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.FileField(default='', upload_to='user_imgs'),
        ),
    ]
