# Generated by Django 4.2.5 on 2023-10-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0004_imagesegment_images_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSegment',
        ),
    ]
