# Generated by Django 4.2.5 on 2023-11-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0006_imagesegment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesegment',
            old_name='land',
            new_name='segment',
        ),
        migrations.RemoveField(
            model_name='imagesegment',
            name='water',
        ),
    ]
