# Generated by Django 4.2.5 on 2023-11-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0007_rename_land_imagesegment_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSimilarity',
            fields=[
                ('img1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='detect_map.images')),
                ('img2', models.FileField(default='', upload_to='user_imgs_similarity')),
                ('img_result', models.FileField(default='', upload_to='user_imgs_similarity')),
            ],
        ),
    ]
