# Generated by Django 4.2.5 on 2024-01-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0010_imagesimilarity_img_similarity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRGB',
            fields=[
                ('img_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='detect_map.images')),
                ('rgb', models.FileField(default='', upload_to='rgb_imgs')),
            ],
        ),
    ]
