# Generated by Django 4.2.5 on 2024-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_map', '0011_imagergb'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagergb',
            name='canny',
            field=models.FileField(default='', upload_to='rgb_imgs'),
        ),
    ]
